#VRML_SIM R2025a utf8
# license: Apache License 2.0
# ButlerServe: TIAGo++ service body with Hey5 hands and a chest tray.
# Docked fleet omits arms so the hotel world stays interactive.
# template language: javascript

EXTERNPROTO "../assets/webots/projects/robots/pal_robotics/tiago_base/protos/TiagoBase.proto"
EXTERNPROTO "../assets/webots/projects/robots/pal_robotics/tiago_extensions/protos/TiagoBody.proto"
EXTERNPROTO "../assets/webots/projects/robots/pal_robotics/tiago_extensions/protos/TiagoRightArm.proto"
EXTERNPROTO "../assets/webots/projects/robots/pal_robotics/tiago_extensions/protos/TiagoLeftArm.proto"
EXTERNPROTO "../assets/webots/projects/robots/pal_robotics/tiago_extensions/protos/TiagoRightHey5.proto"
EXTERNPROTO "../assets/webots/projects/robots/pal_robotics/tiago_extensions/protos/TiagoLeftHey5.proto"
EXTERNPROTO "ButlerTray.proto"

PROTO ButlerServe [
  field  SFVec3f     translation           0 0 0.095
  field  SFRotation  rotation              0 0 1 0
  field  SFString    name                  "servebot-1"
  field  SFString    controller            "butler_serve"
  field  MFString    controllerArgs        []
  field  SFString    window                ""
  field  SFString    customData            ""
  field  SFBool      supervisor            FALSE
  field  SFBool      synchronization       FALSE
  field  SFBool      selfCollision         FALSE
  field  SFBool      locked                FALSE
  field  SFBool      docked                FALSE
  field  MFNode      cameraSlot            []
  field  SFNode      endEffectorRightSlot  TiagoRightHey5 { name "right" }
  field  SFNode      endEffectorLeftSlot   TiagoLeftHey5 { name "left" }
  field  MFNode      lidarSlot             []
  field  SFNode      plateSlot             NULL
  field  SFNode      glassSlot             NULL
  field  SFNode      wineglassSlot         NULL
  field  SFNode      boxSlot               NULL
]
{
  TiagoBase {
    translation IS translation
    rotation IS rotation
    controller IS controller
    controllerArgs IS controllerArgs
    window IS window
    customData IS customData
    supervisor IS supervisor
    synchronization IS synchronization
    selfCollision IS selfCollision
    locked IS locked
    name IS name
    model "ButlerServe"
    bodySlot [
      TiagoBody {
        cameraSlot IS cameraSlot
        %< if (!fields.docked.value) { >%
        rightArmSlot TiagoRightArm {
          endEffectorSlot IS endEffectorRightSlot
        }
        leftArmSlot TiagoLeftArm {
          endEffectorSlot IS endEffectorLeftSlot
        }
        %< } >%
        frontArmSlot ButlerTray {
          plateSlot IS plateSlot
          glassSlot IS glassSlot
          wineglassSlot IS wineglassSlot
          boxSlot IS boxSlot
        }
      }
    ]
    lidarSlot IS lidarSlot
  }
}
